### ISSUE TITLE
blowup in pa.write_stream -> start_rx

### ISSUE THREAD

**Issue by dankamongmen** [blaa/WaveSync#13]
This is on the receiver side. Python 3.10.1 on Arch. Happens whether or not pipewire/pulseaudio are running.

```
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Using default output device index 15
Assuming maximum chunk delay of 3000.00ms in this setup
Queue empty - waiting
Executing <Task pending name='Task-2' coro=<ChunkPlayer.chunk_player() running at /home/dank/.local/lib/python3.10/site-packages/libwavesync/chunk_player.py:140> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:424> cb=[gather.<locals>._done_callback() at /usr/lib/python3.10/asyncio/tasks.py:714] created at /usr/lib/python3.10/asyncio/tasks.py:634> took 0.255 seconds
Got stream flowing. q_len=3
Traceback (most recent call last):
  File "/home/dank/.local/bin/wavesync", line 7, in <module>
    cli.main()
  File "/home/dank/.local/lib/python3.10/site-packages/libwavesync/cli.py", line 115, in main
    start_rx(args, loop)
  File "/home/dank/.local/lib/python3.10/site-packages/libwavesync/cli.py", line 98, in start_rx
    loop.run_until_complete(tasks)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/dank/.local/lib/python3.10/site-packages/libwavesync/chunk_player.py", line 235, in chunk_player
    self.stream.write(chunk)
  File "/home/dank/.local/lib/python3.10/site-packages/pyaudio.py", line 585, in write
    pa.write_stream(self._stream, frames, num_frames,
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
[grimes](1) $ 
```

let me know anything i can do to assist running this down. `wavesync` doesn't have a `--version`, but it's whatever pip3 pulled down.

**Comment by blaa** [comment]
That looks like a pyaudio problem. Try different `--device-index` numbers. But if that doesn't help I might need to check with newer versions of pyaudio - or maybe finally move it to pyalsa to get better control of under/overwrite.
